---

- hosts: all
  become: true
  tasks: 
  
  - name: install http and ftp package 
    tags: tag1
    package:
      name: 
        - "{{http_server}}"
        - "{{ftp_server}}"
      update_cache: true
    when: ansible_distribution == "Fedora" 

- hosts: web_file_server
  become: true
  tasks:
    - name: install ftp and http packages
      tags: tag2
      package:
        name:
          - httpd
          - vsftpd 
        state: latest
        update_cache: true
